### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by jfgvandeursen** [doriguzzi/flad-federated-learning-ddos#1]
Can you help me which data file i should download actually it has zip files not pcap files on your provided links

**Comment by hz4970** [comment]
Can you tell me how to separate the extracted pcap file into 13 data sets, each containing samples of benign traffic and one type of attack? Does this separation work require some tools to implement?

**Comment by whz11** [comment]
> Hello,
> 
> I guess you are referring to the CIC-DDoS2019 dataset. You are right, the dataset consists of zip files. Two of them contain cvs files with the labels. The others contains traffic traces in pcap format. Just unzip them e select the pcap files you need.
> 
> ![image](https://user-images.githubusercontent.com/1794129/176151211-20e8767e-21b6-4267-ba83-c860ae30ef66.png)
> 
> A good reference for this dataset is the webpage: https://www.unb.ca/cic/datasets/ddos-2019.html.
> 
> Best
> 
> --roberto

How do I label the data in a PCAP file? It seems unworkable to identify the type of attack solely by timestamp, as there's a discrepancy between the current timestamps and those provided in the paper.
