### ISSUE TITLE
Training (clients and subfolders)

### ISSUE THREAD

**Issue by jfgvandeursen** [doriguzzi/flad-federated-learning-ddos#2]
I am unable to do training on what is meaning by creating clients can you explain. How to create subfolders and manage it.

**Comment by doriguzzi** [comment]
Hello,
as written in the referenced paper, the script simulates a network of server and clients, which are all hosted on the same computer. To start the federated training, you have to prepare a folder, in which there is one subfolder for each client. A structure like the following:

![image](https://user-images.githubusercontent.com/1794129/176153115-e89edd20-860c-49bb-aa91-9cba6b8ec35e.png)

In our research, we assumed one attack type per client (so, the name of the folders above), but you can do whatever you want, even giving a portion of every attack to each client (for instance).
Each client's folder must contain the usual training/validation/test files, as obtained by using the LUCID dataset parser:

![image](https://user-images.githubusercontent.com/1794129/176153691-4b407e37-8d0b-4eb3-a166-977b445f24ae.png)

Hope this clarifies.

All the best

--roberto
