### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by hz4970** [doriguzzi/flad-federated-learning-ddos#3]
May I ask how to divide pcap file into 13 small data sets, and each data set contains only one attack type? What method is adopted in this paper to achieve pacp file segmentation?  Thanks.

**Comment by doriguzzi** [comment]
Hi,
first I extracted from the pcap files the packets with IP addresses consistent with the attacks: 172.16.0.5 (attacker), 192.168.50.1, 192.168.50.4 (victims). Then I grouped them into various attacks using their timestamp and the information on the time-attack reported here: https://www.unb.ca/cic/datasets/ddos-2019.html. Pay attention that there can be a shift between the timestamp reported by tcpdump and the time intervals reported on the web page. See also here about this issue: https://www.xmodulo.com/tcpdump-cheat-sheet-examples.html
Finally, I checked the pcap files with wireshark to ensure that only the packets of one attack were present in each pcap file. 

Hope this clarifies.

Roberto

**Comment by HameemDakheel** [comment]
Hi Roberto,

I have been attempting to replicate your work for over three months now, but I have hit a dead end. Could you please provide additional details on the following points:

1. **Grouping Packets:**
   - Could you provide more details on how you grouped the packets into various attacks using timestamps? Specifically, what criteria or method did you use to determine the grouping based on timestamps?

2. **Handling Timestamp Shifts:**
   - How did you handle the potential shift between the timestamps reported by tcpdump and the time intervals reported on the web page? Did you apply any specific offset or adjustment?

3. **Tools and Commands:**
   - Could you specify the exact commands or tools you used to extract the packets from the pcap files? This includes any tcpdump filters or scripts you applied.

4. **Verification with Wireshark:**
   - What steps did you take in Wireshark to ensure that only the packets of one attack were present in each pcap file? Were there any specific filters or visual inspections involved?

5. **Additional Resources:**
   - Are there any additional resources or documentation you referred to during your process that might be helpful for me to understand or replicate your approach? If possible, could you provide me with the preprocessed data you used? This would greatly assist me.
 

Your insights will be invaluable for my work.

Thank you,
Hameem
