### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by MohamadAminSoltani** [doriguzzi/flad-federated-learning-ddos#4]
I hope this message finds you well. I'm encountering an issue while attempting to download the dataset from this [link](https://www.unb.ca/cic/datasets/ddos-2019.html), and I'm receiving the following error:
`"read tcp4 196.244.192.206:20279->205.174.165.80:80: i/o timeout."`
Do you happen to have a solution or any guidance on resolving this?

**Comment by doriguzzi** [comment]
Try this: http://205.174.165.80/CICDataset/CICDDoS2019/
