### ISSUE TITLE
dataset split

### ISSUE THREAD

**Issue by flylzj** [doriguzzi/flad-federated-learning-ddos#5]
Hello,I download the dataset from https://www.unb.ca/cic/datasets/ddos-2019.html. But how can I split dataset like this
![image](https://github.com/doriguzzi/flad-federated-learning-ddos/assets/26559515/4cd66fc3-02cf-499e-915a-daea0c2275f9)

**Comment by doriguzzi** [comment]
Hi,
the only way to split the dataset like that is to rely on the tables that you can find at https://www.unb.ca/cic/datasets/ddos-2019.html, where the authors provide the "attack time" for each attack type. Using this information, you can use tcpdump or editcap to extract the relevant packets from the pcap files of the dataset. 
It is a boring job, I know, but I did not find a better way.

I hope this helps.

Roberto
